site_name: nobias advanced scripting

nav:
  - Home:
      - index.md
  - course/installation/installing_fiji.md
  - course/installation/starting_macro.md
  - Introduction:
      - course/introduction/index.md
      - course/introduction/print.md
      - course/introduction/print_exercises.md
      - course/introduction/variables.md
      - course/introduction/variables_exercises.md
      - course/introduction/arrays.md
      - course/introduction/arrays_exercises.md
      - course/introduction/strings.md
      - course/introduction/strings_exercises.md
      - course/introduction/loops.md
      - course/introduction/loops_exercises.md
      - course/introduction/conditionals.md
      - course/introduction/documenting.md
      - course/introduction/functions.md
      - course/introduction/treasure_hunt.md
  - Macro recorder:
      - course/macro_recorder/index.md
      - course/macro_recorder/recording.md
      - course/macro_recorder/loading_images.md
      - course/macro_recorder/splitting_channels.md
      - course/macro_recorder/thresholding.md
  - Advanced Macro:
      - course/advanced_scripting/index.md
      - course/advanced_scripting/functions.md
      - course/advanced_scripting/understanding_parameters.md
      - course/advanced_scripting/error_messages.md
      - course/advanced_scripting/user_interaction.md
  - Pipelines:
      - course/pipelines/index.md
      - Looping through files:
          - course/pipelines/looping_through_files/introduction.md
          - course/pipelines/looping_through_files/getting_file_list.md
          - course/pipelines/looping_through_files/looping_through_list.md
          - course/pipelines/looping_through_files/getting_list_length.md
          - course/pipelines/looping_through_files/opening_files.md
          - course/pipelines/looping_through_files/operating_on_open_files.md
          - course/pipelines/looping_through_files/saving_and_closing_files.md
          - course/pipelines/looping_through_files/summary.md
          - course/pipelines/looping_through_files/simple_gui.md
      - Simple Object Tracking:
          - course/pipelines/simple_object_tracking/introduction.md
          - course/pipelines/simple_object_tracking/navigating_image_stacks.md

  - demo.md

theme:
  name: material
  font: false
  logo: assets/logo.svg
  favicon: assets/logo.svg
  custom_dir: docs/.overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode

  features:
    #- navigation.tabs
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    # - navigation.footer  # next/previous links in footer
    - navigation.content_next # next/previous links bottom of content
    # - navigation.instant  # hard to use with javascript on page load
    # - navigation.tracking
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - navigation.icons

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences
  #- pymdownx.progressbar:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"

plugins:
  # potentially we could use this: https://github.com/jdoiro3/mkdocs-multirepo-plugin
  - search

  # last modified date
  #- git-revision-date-localized:
  #    enable_creation_date: true
  #    type: timeago

  # add committer info
  - git-committers:
      repository: nobias-fht/advanced-scripting
      branch: main
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY

  # minify files
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
      htmlmin_opts:
        remove_comments: true
      css_files:
        - stylesheets/extra.css
        - stylesheets/termynal.css
      js_files:
        - javascripts/extra.js
        - javascripts/termynal.js

  # check spelling in all files, including code documentation
  - spellcheck:
      backends: # the backends you want to use
        - codespell: # or nested configs
            dictionaries: [clear, rare]

watch:
  - docs

extra_css:
  - stylesheets/termynal.css
  - stylesheets/extra.css

extra_javascript:
  - javascripts/termynal.js
  - javascripts/extra.js
